config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/index', as: :dashboards
  delete '/logout', to: 'logins#destroy', as: 'logout'

  resources :logins, only: %i[new create]
  resources :registrations, only: %i[new create]
  resources :posts, only: [:new, :create, :index, :edit, :update, :show]

  root 'dashboards#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true, length: { in: 10..5000 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    user = User.find_by(id: session[:user_id])
    redirect_to posts_path unless user
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
    user = User.find_by(id: session[:user_id])
    redirect_to posts_path if user
    @user = User.new
  end

  def create
    @user = User.find_by(login_params)

    if @user
      session[:user_id] = @user.id
      redirect_to dashboards_path
    else
      flash[:alert] = "Email or password is invalid!"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "You have been logged out!"
  end

  private

    def login_params
      params.require(:user).permit(:email, :password)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :require_author, only: [:edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = session[:user_id]

    if @post.save
      redirect_to posts_path, notice: "You have successfully created a post."

    else
      flash[:alert] = "Couldn't save the post! Please check the errors below. Errors: " + @post.errors.full_messages.join(", ")
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def index
    @posts = Post.all
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    if @post.update(post_params)
      redirect_to dashboards_path, notice: "You have successfully updated the post."
    else
      flash[:alert] = "Couldn't update the post!"
      render :edit, status: :unprocessable_entity
    end

    def destroy
      @post.destroy
      redirect_to dashboards_path, notice: "You have successfully deleted the post."
    end
  end

  private

    def post_params
      params.require(:post).permit(:title, :body)
    end

    def require_login
      unless session[:user_id]
        flash[:alert] = "Please login to continue."
        redirect_to new_login_path
      end
    end

    def set_post
      @post = Post.find(params[:id])
    end

    def require_author
      unless @post.user_id == session[:user_id]
        flash[:alert] = "You are not authorized to perform this action."
        redirect_to dashboards_path
      end
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    user = User.find_by(id: session[:user_id])
    redirect_to dashboards_path if user
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to new_login_path, notice: "You have successfully registered. Please login to continue."
    else
      flash[:alert] = "Couldn't save the User!"
      render :new, status: :unprocessable_entity
    end
  end

    private

    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/dashboards/index.html.erb
<h1>Welcome</h1>

<%= link_to "Create a new post", new_post_path %> |
<%= link_to "See all posts", posts_path %>

<% if session[:user_id] %>
  <%= button_to 'Disconnect', logout_path, method: :delete %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthenticationMixandgo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div><%= notice %></div>
    <div><%= alert %></div>
    <%= yield %>
  </body>
</html>

app/views/logins/new.html.erb
<h1>Log in</h1>

<%= form_with model: @user, url: logins_path do |form| %>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.submit "Log In" %>
  </div>
<% end %>

<%= link_to 'Sign Up', new_registration_path %> |
<%= link_to 'Home', root_path %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_with(model: @post) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to "Return to posts", posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<% @posts.each do |post| %>
  <a href="<%= post_path(post) %>">
    <h4><%= post.title %> by <%= post.user.email %></h4>
  </a>
<% end %>

<%= link_to 'New Post', new_post_path %> |
<%= link_to 'Home', root_path %>

app/views/posts/new.html.erb
<h1>Post</h1>

<%= form_with model: @post do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Home', root_path %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p>By <%= @post.user.email %></p>
<p><%= @post.body %></p>

<% if session[:user_id] == @post.user_id %>
  <%= link_to "Edit", edit_post_path(@post) %> |
<% end %>

<%= link_to "Return to posts", posts_path %>